Repository kor1k/final_project_group2, pull requests merged in 2019-03, with the labels that each got.

#6 @yamnyk | add team code conventions
  conventions.md
Labels: good first issue

#10 @kor1k | added stylelint
  README.md
  frontend/.gitignore
  frontend/.stylelintcache
  frontend/.stylelintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.js
Labels: enhancement

#5 @kor1k | Create README.md
  README.md
Labels: WIP

#11 @kor1k | sonarCloud
  .travis.yml
  sonar-project.properties
Labels: WIP
